/*
 * This source file was generated by the Gradle 'init' task
 */
package ticket.booking;

import ticket.booking.entities.Train;
import ticket.booking.services.UserBookingService;

import java.io.BufferedReader;
import java.io.InputStreamReader;
import java.io.IOException;
import java.util.List;

public class App {

    // -------- small helpers (keep it simple) --------
    private static String prompt(BufferedReader br, String label) throws IOException {
        System.out.print(label);
        return br.readLine().trim();
    }

    private static void showMainMenu() {
        System.out.println("=== Welcome to IRCTC Booking App ===");
        System.out.println("1. Sign Up");
        System.out.println("2. Login");
        System.out.println("3. Exit");
        System.out.print("Enter choice: ");
    }

    private static void showUserMenu() {
        System.out.println("\n--- Menu ---");
        System.out.println("1. View My Bookings");
        System.out.println("2. Cancel a Booking (by Ticket ID)");
        System.out.println("3. Book a Ticket");
        System.out.println("4. Logout");
        System.out.print("Enter Choice: ");
    }

    private static void handleBooking(UserBookingService service, BufferedReader br) throws IOException {
        System.out.println("\nAvailable trains:");
        service.listTrains();

        String from = prompt(br, "From: ");
        String to   = prompt(br, "To: ");

        List<Train> options = service.searchTrain(from, to);
        if (options.isEmpty()) {
            System.out.println("No Trains Found for that route");
            return;
        }

        System.out.println("Matching trains:");
        for (Train t : options) {
            System.out.println(" - Train " + t.getTrainNo() + " (" + t.getTrainId() + ")");
        }

        String trainNo = prompt(br, "Choose Train No (or ID): ");
        String dateStr = prompt(br, "Date (dd-MM-yyyy): ");

        boolean ok = service.bookTicket(from, to, dateStr, trainNo); // correct order
        System.out.println(ok ? "Booked successfully." : "Booking failed.");
    }
    // -------------------------------------------------

    public static void main(String[] args) {
        try {
            UserBookingService service = new UserBookingService();
            BufferedReader br = new BufferedReader(new InputStreamReader(System.in));

            while (true) { // main menu loop
                showMainMenu();
                String choice = br.readLine();

                if ("1".equals(choice)) {
                    String name = prompt(br, "Enter name: ");
                    String password = prompt(br, "Enter password: ");
                    service.signUp(name, password);

                } else if ("2".equals(choice)) {
                    String name = prompt(br, "Enter name: ");
                    String password = prompt(br, "Enter password: ");

                    if (!service.login(name, password)) {
                        System.out.println("❌ Login Failed");
                        continue;
                    }
                    System.out.println("✅ Logged In Successfully");

                    // logged-in loop
                    while (true) {
                        showUserMenu();
                        String c = br.readLine();

                        if ("1".equals(c)) {
                            service.fetchBooking();

                        } else if ("2".equals(c)) {
                            String id = prompt(br, "Enter Ticket ID to cancel: ");
                            service.cancelBookingById(id);

                        } else if ("3".equals(c)) {
                            handleBooking(service, br);

                        } else if ("4".equals(c)) {
                            System.out.println("Logged Out, Thanks For Visiting Irctc.");
                            break; // back to main menu

                        } else {
                            System.out.println("Invalid Choice");
                        }
                    }

                } else if ("3".equals(choice)) {
                    System.out.println("Bye !!");
                    break;

                } else {
                    System.out.println("Invalid choice");
                }
            }
        } catch (Throwable t) {
            System.out.println("=== ERROR IN MAIN ===");
            t.printStackTrace();
        }
    }
}
