/*
 * This source file was generated by the Gradle 'init' task
 */
package ticket.booking;


import ticket.booking.services.UserBookingService;

import java.io.BufferedReader;
import java.io.InputStreamReader;

public class App {
    public static void main(String[] args)  {

        try {
            UserBookingService service = new UserBookingService();
            BufferedReader br = new BufferedReader(new InputStreamReader(System.in));

            System.out.println("=== Welcome to IRCTC Booking App ===");
            System.out.println("1. Login");
            System.out.println("2. Exit");
            System.out.print("Enter choice: ");
            String choice = br.readLine();

            if ("1".equals(choice)) {
                System.out.print("Enter name: ");
                String name = br.readLine();

                System.out.print("Enter password: ");
                String password = br.readLine();

                if (!service.login(name, password)) {
                    System.out.println("❌ Login Failed");
                    return;
                }

                System.out.println("✅ Logged In Successfully");

                while (true) {
                    System.out.println("\n--- Menu ---");
                    System.out.println("1. View My Bookings");
                    System.out.println("2. Logout");
                    System.out.print("Enter Choice: ");
                    String c = br.readLine();

                    if ("1".equals(c)) {
                        service.fetchBooking();
                    } else if ("2".equals(c)) {
                        System.out.println("👋 Logged Out.");
                        break;
                    } else {
                        System.out.println("Invalid Choice");
                    }
                }
            } else {
                System.out.println("Bye !!");
            }
        } catch (Throwable t) {
            System.out.println("=== ERROR IN MAIN ===");
            t.printStackTrace();  // <-- this will show the real cause of the Gradle failure
        }
    }
    }

